version: "3.0"
services:
  mysql_server:
    image: mysql
    restart: always
    ports:
      - 3306:3306 
    volumes:
      - ./mysql_data:/var/lib/mysql
      # - ./chatbot.sql:/docker-entrypoint-initdb.d/chatbot.sql
    environment:
      -  MYSQL_ALLOW_EMPTY_PASSWORD=true
  # frontend:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
